POST http://localhost:3001/api/blogs/60f5be1e69482041d8f296c3/comments
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjYwZjViZTFkNjk0ODIwNDFkOGYyOTZjMiIsImlhdCI6MTYyNjgxNDcwMCwiZXhwIjoxNjI2ODE4MzAwfQ.x1Hy_y_YWM4jcKeIYDTJr13ATV1ho8pUvbJ-iyMK-YE

{
    "comments": [
        "this is a test",
        "test2"
    ]
}